import { ref, computed } from 'vue'
import { defineStore } from 'pinia'
import type { Project, ProjectCategory } from '@/types'

// import PortfolioPic from '../assets/images/Portfolio2.png' // hidden from UI (kept for future use)
import BarcodeCrudPic from '../assets/images/BarcodeCrud.png'
import EmployeeManagementPic from '../assets/images/Employee.png'
// import CrapsGamePic from '../assets/images/Craps.png' // hidden from UI (kept for future use)
// import DocQuizPipelinePic from '../assets/images/CommandLineParser.png' // hidden from UI (kept for future use)
import SmartResumePic from '../assets/images/SmartResume.png'
import FolioPic from '../assets/images/Folio.png'

export const useProjectsStore = defineStore('projects', () => {
  const projects = ref<Project[]>([
    /* Portfolio Website — hidden from UI (kept for future use)
    {
      id: 1,
      title: 'Portfolio Website',
      description:
        'This responsive portfolio website showcasing projects and skills, built with modern web technologies and best practices.',
      longDescription:
        'A modern, responsive portfolio website built with Vue 3, TypeScript, and Vuetify 3. Features include dark/light theme toggle, smooth animations, optimized performance, and a clean, professional design. Deployed with automated CI/CD pipeline.',
      image: PortfolioPic,
      technologies: [
        {
          category: 'Programming Languages',
          icon: 'mdi-code-json',
          color: 'blue',
          skills: ['JavaScript ES6+', 'TypeScript'],
        },
        {
          category: 'Frontend Technologies',
          icon: 'mdi-monitor',
          color: 'green',
          skills: ['Vue 3', 'Vuetify 3', 'Vue Router 4', 'Pinia', 'CSS'],
        },
        {
          category: 'Backend Technologies',
          icon: 'mdi-server',
          color: 'orange',
          skills: ['Node.js'],
        },
        {
          category: 'Databases & Storage',
          icon: 'mdi-database-outline',
          color: 'red',
          skills: [],
        },
        {
          category: 'Cloud & DevOps',
          icon: 'mdi-cloud-outline',
          color: 'purple',
          skills: ['CI/CD', 'Git/GitHub', 'GitHub Actions'],
        },
        {
          category: 'Tools & Others',
          icon: 'mdi-tools',
          color: 'brown',
          skills: [
            'Vite',
            'NPM',
            'UI/UX Design',
            'Responsive Design',
            'Vitest',
            'Unit Tests',
            'Component Testing',
          ],
        },
      ],
      liveUrl: 'https://jameslittlefield.net',
      githubUrl: 'https://github.com/musicteachj/portfolio',
      featured: false,
      category: 'Frontend',
      year: 2025,
      status: 'completed',
      features: [
        'Responsive design optimized for all devices',
        'Dark/light theme toggle with persistence',
        'Smooth scroll animations and transitions',
        'TypeScript for enhanced code quality',
        'SEO optimized with proper meta tags',
        'Fast loading with Vite build optimization',
        'Accessible design following WCAG guidelines',
        'Continuous deployment with GitHub Actions',
      ],
      viewport: ['desktop', 'mobile', 'tablet'],
    },
    */
    {
      id: 2,
      title: 'Barcode Gen',
      description:
        'A full-stack barcode app for scanning, creating, storing, and printing professional barcodes. Built with Vue.js/Express.js, supports 8+ types with cloud storage.',
      longDescription:
        'Barcode Gen is a comprehensive barcode lifecycle management system that enables users to scan existing barcodes using their device camera or manually create new ones with real-time validation and preview. The application supports 8+ professional barcode formats including EAN-13, UPC, CODE128, and CODE39, with automatic check digit calculation and industry-standard compliance. Built as a full-stack TypeScript application with Vue.js frontend and Express.js backend, it features MongoDB cloud storage, professional print layouts, and a mobile-optimized responsive design with fullscreen scanning interface. Users can manage up to 20 barcodes with complete CRUD operations, including bulk printing capabilities and haptic feedback for enhanced mobile experience. The application is production-ready with AWS deployment using ECS for container orchestration on EC2 instances, Route 53 for DNS management, CloudFront for content delivery, Docker containerization, comprehensive error handling, Jest unit tests, and health monitoring endpoints.',
      image: BarcodeCrudPic,
      technologies: [
        {
          category: 'Programming Languages',
          icon: 'mdi-code-json',
          color: 'blue',
          skills: ['JavaScript ES6+', 'TypeScript'],
        },
        {
          category: 'Frontend Technologies',
          icon: 'mdi-monitor',
          color: 'green',
          skills: ['Vue 2', 'Vuetify 2', 'Vuex', 'Vue Router 3', 'CSS', 'Axios'],
        },
        {
          category: 'Backend Technologies',
          icon: 'mdi-server',
          color: 'orange',
          skills: ['Express.js', 'Node.js', 'REST APIs'],
        },
        {
          category: 'Databases & Storage',
          icon: 'mdi-database-outline',
          color: 'red',
          skills: ['MongoDB', 'NoSQL'],
        },
        {
          category: 'Cloud & DevOps',
          icon: 'mdi-cloud-outline',
          color: 'purple',
          skills: [
            'CI/CD',
            'Docker',
            'Git/GitHub',
            'GitHub Actions',
            'AWS',
            'CloudFront',
            'S3',
            'Route 53',
            'EC2',
            'ECS',
          ],
        },
        {
          category: 'Tools & Others',
          icon: 'mdi-tools',
          color: 'brown',
          skills: [
            'Vue CLI',
            'NPM',
            'Jest Unit Tests',
            'UI/UX Design',
            'Quagga scanner',
            'PrintD',
            'Vuelidate',
            'Vue-barcode',
            'UI/UX Design',
            'Responsive Design',
          ],
        },
      ],
      liveUrl: 'https://barcode.jameslittlefield.net',
      githubUrl: 'https://github.com/musicteachj/barcode-crud',
      featured: true,
      category: 'Full Stack',
      year: 2025,
      status: 'completed',
      features: [
        'Real-time barcode scanning using device camera with Quagga.js',
        'Support for 8+ barcode types (EAN-13, UPC, CODE128, etc.)',
        'MongoDB cloud storage with 20-barcode limit management',
        'Professional print functionality for individual/bulk printing',
        'Mobile-optimized responsive design with fullscreen scanning',
        'Full-stack TypeScript with Vue.js frontend & Express.js API',
        'Real-time barcode preview and validation with form checks',
        'Jest unit tests for frontend and backend',
        'Production-ready AWS deployment with ECS, EC2, Route 53 & monitoring',
      ],
      viewport: ['desktop', 'mobile', 'tablet'],
    },
    {
      id: 3,
      title: 'Employee Management System',
      description:
        'Full‑stack HR console for employee records, org charts, bulk updates, and performance reviews, plus a Workforce Insights Assistant: a Claude chatbot that answers questions straight from live employee and analytics data. Vue 3 frontend, FastAPI backend, JWT auth built from scratch.',
      longDescription:
        'Employee Management System is a full-stack web application for centralizing and streamlining HR operations that lets you create, update, search, and organize employee records; assign managers; visualize the org chart; perform bulk updates; and manage performance reviews end-to-end (scheduling, conducting, tracking, and monitoring overdue reviews), with an interactive analytics dashboard that surfaces key insights like department and status distributions, job levels, salaries, and hiring/performance trends via rich charts. Its standout feature is the Workforce Insights Assistant, a Claude-powered chatbot that answers HR questions through an agentic tool-use loop: the model calls real backend functions like search_employees, get_workforce_analytics, get_overdue_reviews, and get_direct_reports, so every answer is grounded in live data rather than guessed, and responses stream token by token over SSE. Privacy guards keep sensitive fields such as salaries, SSNs, and personal contact details out of individual results. The frontend is built with Vue 3, Vuetify, Pinia, and Chart.js, while the backend uses FastAPI with async MongoDB (Motor) and the Anthropic SDK, featuring JWT authentication, environment-based configuration, and Vite-powered local development with SPA serving in production. The application is deployed on AWS using ECS Fargate for serverless container orchestration, ECR for Docker image registry, Application Load Balancer for HTTPS routing with host-based rules, Route 53 for DNS management, AWS Secrets Manager for secure credential storage (MongoDB and JWT secrets), and CloudWatch Logs for monitoring, with the database hosted on MongoDB Atlas for managed, scalable data persistence. The entire stack is containerized using multi-stage Docker builds and deployed via a GitHub Actions CI/CD pipeline, enabling automated builds and deployments on every push to main.',
      image: EmployeeManagementPic,
      technologies: [
        {
          category: 'AI & Agentic Development',
          icon: 'mdi-robot-outline',
          color: 'blue',
          skills: [
            'Claude / LLM Integration',
            'Tool Use / Function Calling',
            'Agentic Development',
          ],
        },
        {
          category: 'Programming Languages',
          icon: 'mdi-code-json',
          color: 'blue',
          skills: ['JavaScript ES6+', 'TypeScript', 'Python'],
        },
        {
          category: 'Frontend Technologies',
          icon: 'mdi-monitor',
          color: 'green',
          skills: ['Vue 3', 'Vuetify 3', 'Vue Router 4', 'Pinia', 'CSS', 'Axios'],
        },
        {
          category: 'Backend Technologies',
          icon: 'mdi-server',
          color: 'orange',
          skills: ['FastAPI', 'Pydantic', 'Motor'],
        },
        {
          category: 'Databases & Storage',
          icon: 'mdi-database-outline',
          color: 'red',
          skills: ['MongoDB', 'NoSQL'],
        },
        {
          category: 'Cloud & DevOps',
          icon: 'mdi-cloud-outline',
          color: 'purple',
          skills: [
            'CI/CD',
            'Docker',
            'Git/GitHub',
            'GitHub Actions',
            'AWS',
            'ECS',
            'EC2',
            'Route 53',
          ],
        },
        {
          category: 'Tools & Others',
          icon: 'mdi-tools',
          color: 'brown',
          skills: [
            'Vite',
            'NPM',
            'Vee-validate',
            'Chart.js',
            'JWT',
            'PIP',
            'Zod',
            'XLSX',
            'Anthropic SDK',
            'SSE Streaming',
            'marked',
            'DOMPurify',
            'dayjs',
            'pandas',
            'numpy',
            'UI/UX Design',
            'Responsive Design',
          ],
        },
      ],
      liveUrl: 'https://employees.jameslittlefield.net',
      githubUrl: 'https://github.com/musicteachj/employee-management-system',
      featured: true,
      category: 'Full Stack',
      year: 2025,
      status: 'completed',
      features: [
        'Workforce Insights Assistant: a Claude chatbot answering HR questions from live data',
        'Agentic tool-use loop calling real backend functions (search, analytics, reviews, reports)',
        'Grounded, no-hallucination answers streamed token-by-token over SSE',
        'Privacy guards keep salaries, SSNs, and contact details out of chatbot results',
        'JWT authentication built from scratch (no external auth libraries)',
        'Full-stack TypeScript + Python with type-safe validation',
        'Interactive analytics dashboard with 8 real-time chart visualizations',
        'Advanced multi-criteria employee search and filtering',
        'Bulk operations for managing multiple employees simultaneously',
        'Interactive organizational hierarchy chart with manager reporting',
        'Performance review tracking and scheduling system',
        'RESTful API with auto-generated FastAPI documentation',
        'Reactive state management using Pinia stores',
        'Responsive Material Design UI with Vuetify components',
        'MongoDB with async operations using Motor driver',
        'Docker containerized and AWS cloud-ready architecture',
        'Protected routes with token-based stateless authentication',
        'Password hashing with bcrypt for security best practices',
        'Vue 3 Composition API with modern reactive programming patterns',
      ],
      viewport: ['desktop', 'tablet'],
    },
    /* Craps Game & DocQuiz Pipeline (Command Line Parser) — hidden from UI (kept for future use)
    {
      id: 4,
      title: 'Craps Game',
      description:
        'Craps is an interactive web-based dice game that simulates a simplified version of casino craps. Built with React.js, Vite, Styled-Components, and Vitest for testing.',
      longDescription:
        'An interactive web-based implementation of simplified craps featuring a React-based UI with animated dice, real-time game state management, and comprehensive game statistics. Built with TypeScript, styled-components, and Vitest for testing, this application demonstrates modern frontend development practices including component composition, type safety, and test-driven development.',
      image: CrapsGamePic,
      technologies: [
        {
          category: 'Programming Languages',
          icon: 'mdi-code-json',
          color: 'blue',
          skills: ['JavaScript ES6+', 'TypeScript'],
        },
        {
          category: 'Frontend Technologies',
          icon: 'mdi-monitor',
          color: 'green',
          skills: ['React.js', 'React DOM', 'CSS', 'Styled-Components'],
        },
        {
          category: 'Backend Technologies',
          icon: 'mdi-server',
          color: 'orange',
          skills: ['Node.js'],
        },
        {
          category: 'Databases & Storage',
          icon: 'mdi-database-outline',
          color: 'red',
          skills: [],
        },
        {
          category: 'Cloud & DevOps',
          icon: 'mdi-cloud-outline',
          color: 'purple',
          skills: ['Git/GitHub', 'GitHub Actions', 'CI/CD', 'GitHub Pages'],
        },
        {
          category: 'Tools & Others',
          icon: 'mdi-tools',
          color: 'brown',
          skills: [
            'Vite',
            'Vitest',
            'ESLint',
            'Yarn',
            'Cursor AI',
            'Claude AI',
            'Agentic Programming',
          ],
        },
      ],
      liveUrl: 'https://musicteachj.github.io/city-base-craps/',
      githubUrl: 'https://github.com/musicteachj/city-base-craps',
      featured: true,
      category: 'Frontend',
      year: 2025,
      status: 'completed',
      features: [
        'Interactive casino-style craps game with simplified ruleset',
        'Built with React 18 and TypeScript for type safety',
        'Real-time bankroll management and betting system',
        'Animated 3D CSS dice displaying actual roll values',
        'Comprehensive input validation with user-friendly error messages',
        'Configurable bankroll ($5-$1000) and bet amounts',
        'Game statistics showing total wins/losses and final bankroll',
        'Fully responsive design for mobile, tablet, and desktop',
        'WCAG accessibility compliant with semantic HTML and ARIA labels',
        'Styled with styled-components for component-scoped CSS',
        'Built with Vite for fast development and optimized production builds',
        'Comprehensive unit tests using Vitest and React Testing Library',
        'Automated deployment to GitHub Pages via GitHub Actions',
      ],
      viewport: ['desktop', 'mobile', 'tablet'],
    },
    {
      id: 5,
      title: 'DocQuiz Pipeline',
      description:
        'A full-stack application demonstrating document parsing, modern web development, and DevOps automation. Built with Python, Vue 3/TypeScript, and deployed via GitHub Actions CI/CD pipeline. Transforms Word documents into an interactive quiz with persistent state management.',
      longDescription:
        'DocQuiz Pipeline is a full-stack web application that automatically converts Microsoft Word documents into interactive quiz experiences with complete CI/CD automation. The project features a custom Python parser that extracts quiz questions from .docx files using only standard library modules, outputting validated JSON data. The frontend is built with Vue 3, TypeScript, and Vite, featuring localStorage persistence for automatic progress saving, real-time progress tracking, comprehensive results review, and responsive design. A GitHub Actions pipeline automatically regenerates quiz data, runs automated tests (11 backend tests with Python unittest, 22 frontend tests with Vitest), builds the production bundle, and deploys to GitHub Pages on every push. The application demonstrates proficiency in Python, Vue 3 Composition API, TypeScript, automated testing, DevOps practices, and modern software architecture.',
      image: DocQuizPipelinePic,
      technologies: [
        {
          category: 'Programming Languages',
          icon: 'mdi-code-json',
          color: 'blue',
          skills: ['Python', 'JavaScript ES6+', 'TypeScript'],
        },
        {
          category: 'Frontend Technologies',
          icon: 'mdi-monitor',
          color: 'green',
          skills: ['Vue 3', 'CSS'],
        },
        {
          category: 'Backend Technologies',
          icon: 'mdi-server',
          color: 'orange',
          skills: ['Python CLI'],
        },
        {
          category: 'Databases & Storage',
          icon: 'mdi-database-outline',
          color: 'red',
          skills: ['Browser localStorage'],
        },
        {
          category: 'Cloud & DevOps',
          icon: 'mdi-cloud-outline',
          color: 'purple',
          skills: ['Git/GitHub', 'GitHub Actions', 'CI/CD', 'GitHub Pages'],
        },
        {
          category: 'Tools & Others',
          icon: 'mdi-tools',
          color: 'brown',
          skills: ['Node.js', 'Vitest', 'Python unittest', 'Vue Test Utils'],
        },
      ],
      liveUrl: 'https://musicteachj.github.io/command-line-parser/',
      githubUrl: 'https://github.com/musicteachj/command-line-parser',
      featured: true,
      category: 'Frontend',
      year: 2025,
      status: 'completed',
      features: [
        'Custom Python CLI parser that extracts quiz questions from Microsoft Word (.docx) files',
        'Zero-dependency parsing using Python standard library (zipfile, xml.etree, argparse)',
        'Interactive quiz interface built with Vue 3 Composition API and TypeScript',
        'Automatic progress saving with localStorage persistence - resume anytime without losing answers',
        'Real-time progress tracking showing completion percentage',
        'Comprehensive results review displaying all questions with user answers highlighted',
        'Responsive design that works seamlessly across desktop and mobile devices',
        'Automated CI/CD pipeline using GitHub Actions for continuous deployment',
        'Automated testing with 11 backend tests (Python unittest) and 22 frontend tests (Vitest)',
        'One-push deployment: update Word document, commit, and the app rebuilds automatically',
        'Fast development and optimized builds with Vite bundler',
        'Type-safe codebase with TypeScript strict mode enabled',
        'Clean, accessible UI with keyboard navigation support',
        'Component-based architecture with clear separation of concerns',
        'Deployed on GitHub Pages as a static single-page application',
      ],
      viewport: ['desktop', 'tablet', 'mobile'],
    },
    */
    {
      id: 6,
      title: 'Smart Resume Builder',
      description:
        'An AI-powered resume builder: a React 19 front end with a split-screen editor and live, print-accurate preview, backed by a Django REST API. Claude sharpens bullet points, writes summaries, and tailors a resume to a job description with an ATS match score and missing-keyword suggestions. One-click PDF export and multi-resume management.',
      longDescription:
        'Smart Resume Builder is a full-stack, AI-assisted resume platform. The front end is React 19 + TypeScript (Vite, Tailwind, shadcn/ui, Zustand for client state, TanStack Query for server state, React Hook Form with Zod validation), and the back end is Python 3.12 / Django 5.2 with Django REST Framework, SimpleJWT auth, and PostgreSQL 15. Users register with email and password, manage multiple resumes from a dashboard, and edit them in a split-screen form and live preview that autosaves each section: personal info, work history, education, skills, and projects. Claude drives the AI assist, rewriting bullet points, generating professional summaries, and tailoring a resume to a pasted job description, returning an ATS match score plus the keywords the resume is missing; per-user daily and monthly usage limits keep costs in check. Existing resumes can be imported by parsing uploaded .docx (mammoth) and PDF (pdfjs) files, sections reordered by drag and drop (dnd-kit), and the finished document exported to a clean, ATS-safe PDF that matches the on-screen preview. The API is OpenAPI-documented with drf-spectacular and consumed through a fully typed client generated by orval. Everything is containerized with Docker and deploys to AWS ECS/RDS with secrets in AWS Secrets Manager and CI/CD via GitHub Actions.',
      image: SmartResumePic,
      technologies: [
        {
          category: 'AI & Agentic Development',
          icon: 'mdi-robot-outline',
          color: 'blue',
          skills: ['Claude / LLM Integration', 'Prompt Engineering', 'AI Product Design'],
        },
        {
          category: 'Programming Languages',
          icon: 'mdi-code-json',
          color: 'blue',
          skills: ['JavaScript ES6+', 'TypeScript', 'Python', 'SQL'],
        },
        {
          category: 'Frontend Technologies',
          icon: 'mdi-monitor',
          color: 'green',
          skills: [
            'React 19',
            'Tailwind',
            'shadcn/ui',
            'CSS',
            'React Router',
            'React Hook Form',
            'TanStack Query',
            'Zustand',
            'Axios',
          ],
        },
        {
          category: 'Backend Technologies',
          icon: 'mdi-server',
          color: 'orange',
          skills: ['Django', 'Django REST Framework', 'REST APIs'],
        },
        {
          category: 'Databases & Storage',
          icon: 'mdi-database-outline',
          color: 'red',
          skills: ['PostgreSQL'],
        },
        {
          category: 'Cloud & DevOps',
          icon: 'mdi-cloud-outline',
          color: 'purple',
          skills: [
            'Docker',
            'AWS',
            'ECS',
            'ECR',
            'RDS',
            'Secrets Manager',
            'CI/CD',
            'GitHub Actions',
            'Git/GitHub',
          ],
        },
        {
          category: 'Tools & Others',
          icon: 'mdi-tools',
          color: 'brown',
          skills: [
            'Vite',
            'Zod',
            'SimpleJWT',
            'drf-spectacular',
            'orval',
            'Anthropic SDK',
            'mammoth',
            'pdfjs',
            'dnd-kit',
            'Gunicorn',
            'WhiteNoise',
            'Vitest',
            'pytest',
            'UI/UX Design',
            'Responsive Design',
            'Cursor AI',
            'Claude Code',
            'Agentic Programming',
          ],
        },
      ],
      liveUrl: '',
      githubUrl: 'https://github.com/musicteachj/smart-resume-builder',
      featured: true,
      category: 'Full Stack',
      year: 2026,
      status: 'in-progress',
      features: [
        'React 19 + TypeScript front end with a split-screen editor and live, print-accurate preview',
        'Django REST Framework API (Python 3.12) with SimpleJWT auth and PostgreSQL 15',
        'Claude rewrites bullet points and generates professional summaries',
        'Job-description tailoring with an ATS match score and missing-keyword suggestions',
        'Per-user daily and monthly AI usage limits for cost control',
        'Resume import by parsing uploaded .docx (mammoth) and PDF (pdfjs) files',
        'Drag-and-drop section reordering with dnd-kit',
        'One-click ATS-safe PDF export that matches the on-screen preview',
        'Zustand for client state, TanStack Query for server state, React Hook Form + Zod validation',
        'OpenAPI schema via drf-spectacular consumed through an orval-generated typed client',
        'Multi-resume dashboard with autosaving sections',
        'Dockerized services deployed to AWS ECS/RDS with GitHub Actions CI/CD and Secrets Manager',
      ],
      viewport: ['desktop', 'tablet'],
    },
    {
      id: 7,
      title: 'Folio',
      description:
        'A RAG-powered brand content studio. Feed it a brand’s voice guides, best past posts, pillars, and personas; it retrieves the relevant context at generation time so Claude writes on-brand LinkedIn posts and designs matching 1080×1350 image cards where the preview is identical to the exported PNG.',
      longDescription:
        'Folio helps a company sound like itself on LinkedIn. You give it the brand’s raw material (voice and tone guides, strong past posts, content pillars, audience personas, competitor notes) and it embeds and indexes that corpus per workspace. When you write a post, Folio retrieves the pieces of brand context that actually matter for the request and feeds them to Claude, so the copy comes out on-brand instead of generic; retrieval is the whole point, and it is what separates this from a plain prompt-and-response tool. It produces two publish-ready outputs: LinkedIn text posts and designed 1080×1350 image cards exported as pixel-accurate PNGs, with the on-screen preview guaranteed identical to the export. Card copy uses a two-pass approach, streaming natural draft copy into a live preview and then making a strict tool-use call for the structured fields (eyebrow, headline, body, CTA, hashtag) that drive the locked design. Folio is genuinely multi-brand: you manage workspaces in the app, edit each brand’s palette, fonts, logo, and voice, and can let it learn a brand automatically by uploading a logo or brand-guideline image, from which a Claude vision tool-use call proposes named colors, fonts, and a voice to review and apply. You can upload your own brand fonts with full parity across card previews, PNG export, and PDFs, and save named card presets to reuse a look in one click. Visitors can jump straight into a seeded demo brand, "Verdure Materials," to feel the retrieval-driven quality immediately, with destructive actions locked down. The front end is React 19 + TypeScript (Vite, Tailwind, shadcn/ui, Zustand, TanStack Query, React Hook Form with Zod); the back end is FastAPI with async MongoDB (Motor) and Pydantic v2, streaming over SSE. Generation runs on Claude; embeddings use OpenAI text-embedding-3-small; chunking is hand-rolled with langchain-text-splitters against a swappable vector store (Chroma locally, Qdrant in production). Cards render to PNG with Satori and resvg, documents to PDF with ReportLab, and images come from a server-proxied Unsplash integration or direct upload.',
      image: FolioPic,
      technologies: [
        {
          category: 'AI & Agentic Development',
          icon: 'mdi-robot-outline',
          color: 'blue',
          skills: [
            'RAG (Retrieval-Augmented Generation)',
            'Claude / LLM Integration',
            'Tool Use / Function Calling',
            'AI Product Design',
          ],
        },
        {
          category: 'Programming Languages',
          icon: 'mdi-code-json',
          color: 'blue',
          skills: ['TypeScript', 'JavaScript ES6+', 'Python'],
        },
        {
          category: 'Frontend Technologies',
          icon: 'mdi-monitor',
          color: 'green',
          skills: [
            'React 19',
            'Tailwind',
            'shadcn/ui',
            'CSS',
            'React Router',
            'React Hook Form',
            'TanStack Query',
            'Zustand',
            'Axios',
          ],
        },
        {
          category: 'Backend Technologies',
          icon: 'mdi-server',
          color: 'orange',
          skills: ['FastAPI', 'Pydantic', 'Motor'],
        },
        {
          category: 'Databases & Storage',
          icon: 'mdi-database-outline',
          color: 'red',
          skills: ['MongoDB', 'Chroma', 'Qdrant', 'NoSQL'],
        },
        {
          category: 'Cloud & DevOps',
          icon: 'mdi-cloud-outline',
          color: 'purple',
          skills: ['Docker', 'CI/CD', 'GitHub Actions', 'Git/GitHub'],
        },
        {
          category: 'Tools & Others',
          icon: 'mdi-tools',
          color: 'brown',
          skills: [
            'Vite',
            'Zod',
            'JWT',
            'Anthropic SDK',
            'OpenAI Embeddings',
            'langchain-text-splitters',
            'Satori',
            'resvg',
            'ReportLab',
            'Unsplash API',
            'SSE Streaming',
            'Vitest',
            'pytest',
            'UI/UX Design',
            'Responsive Design',
            'Cursor AI',
            'Claude Code',
            'Agentic Programming',
          ],
        },
      ],
      liveUrl: '',
      githubUrl: 'https://github.com/musicteachj/brand-content-studio',
      featured: true,
      category: 'Full Stack',
      year: 2026,
      status: 'in-progress',
      features: [
        'RAG pipeline retrieves per-workspace brand context at generation time for on-brand copy',
        'Generates LinkedIn text posts and designed 1080×1350 image cards',
        'Card preview is pixel-identical to the exported PNG (Satori + resvg)',
        'Two-pass card copy: streamed draft, then a strict tool-use call for structured fields',
        'Multi-brand workspaces with editable palette, fonts, logo, and voice',
        'Brand auto-extraction from an uploaded logo or guideline via a Claude vision tool-use call',
        'Custom brand-font upload with parity across previews, PNG export, and PDFs',
        'Saved card presets to reuse a look in one click',
        'Seeded "Verdure Materials" demo brand with destructive actions locked down',
        'Claude generation streamed over SSE; OpenAI embeddings; swappable Chroma/Qdrant vector store',
        'React 19 + FastAPI (async MongoDB via Motor, Pydantic v2)',
        'PDF documents via ReportLab and server-proxied Unsplash images',
      ],
      viewport: ['desktop', 'tablet'],
    },
  ])

  // Computed properties
  const featuredProjects = computed(() => projects.value.filter((project) => project.featured))

  const categories = computed(() => {
    const cats = [...new Set(projects.value.map((p) => p.category))]
    return ['All', ...cats] as Array<'All' | ProjectCategory>
  })

  // Methods
  const getProjectsByCategory = (category: ProjectCategory | 'All'): Project[] => {
    if (category === 'All') {
      return projects.value
    }
    return projects.value.filter((project) => project.category === category)
  }

  const getProjectById = (id: number): Project | undefined => {
    return projects.value.find((project) => project.id === id)
  }

  return {
    projects,
    featuredProjects,
    categories,
    getProjectsByCategory,
    getProjectById,
  }
})
